### ISSUE TITLE
More 0xed mnemonics

### ISSUE THREAD

**Issue by mortenjc** [kosarev/z80#64]
If only I knew how to fix this myself I would happily make a PR. But I couldn't easily figure out 
how this is done, so:

```
0000 ed b0        ; ldir                 |
0002 ed           ; db 0xed              |
0003 b1           ; or c                 |
0004 ed           ; db 0xed              |
0005 b2           ; or d                 |
0006 ed           ; db 0xed              |
0007 b3           ; or e                 |
0008 ed b8        ; lddr                 |
000a ed           ; db 0xed              |
000b b9           ; cp c                 |
000c ed           ; db 0xed              |
000d ba           ; cp d                 |
000e ed           ; db 0xed              |
000f bb           ; cp e                 |
```

These instructions should be interpreted as
ldir (ok), cpir, inir, otir, lddr (ok), cpdr, indr, otdr respectively, see
https://clrhome.org/table/#ed

**Comment by mortenjc** [comment]
Also holds for these:
<img width="1416" alt="Screenshot 2024-08-12 at 21 43 05" src="https://github.com/user-attachments/assets/cc24bc05-3de5-40be-821b-05075b3ff601">

**Comment by mortenjc** [comment]
And thanks again for this project. I am having a lot of fun using it!

**Comment by kosarev** [comment]
f4bc1a3607749ce6ec24dd45e2533ce685ec42f1 should fix this, thanks!

**Comment by mortenjc** [comment]
Thanks!
